export enum ErrorCode {
  VALIDATION_ERROR = 'VALIDATION_ERROR',
  UNAUTHORIZED = 'UNAUTHORIZED',
  FORBIDDEN = 'FORBIDDEN',
  NOT_FOUND = 'NOT_FOUND',
  CONFLICT = 'CONFLICT',
  INTERNAL_ERROR = 'INTERNAL_ERROR',

  AUTH_INVALID_CREDENTIALS = 'AUTH_INVALID_CREDENTIALS',
  AUTH_EMAIL_ALREADY_REGISTERED = 'AUTH_EMAIL_ALREADY_REGISTERED',

  BOOKING_NOT_FOUND = 'BOOKING_NOT_FOUND',
  BOOKING_EVENT_NOT_FOUND = 'BOOKING_EVENT_NOT_FOUND',
  BOOKING_INSUFFICIENT_SEATS = 'BOOKING_INSUFFICIENT_SEATS',
  BOOKING_DUPLICATE_EVENT = 'BOOKING_DUPLICATE_EVENT',
}
